### ISSUE TITLE
Home page: Adding testimonials section

### ISSUE THREAD

**Issue by MontoneMarcin** [majo44/ac-site#26]
Hi guys,

After meeting with Piotr, we need to add a testimonials section to the home page. It will be located below the video section and "Get in touch" button. 

I'm attaching the design, the section should break the vertical flow of the page, which will focus the attention on this section and also increase the visibility of "get in touch button" for potential leads.

Piotr should deliver few quotes for section until Friday, for now, please create 4 boxes with the same quote. 
![testimonials_section](https://user-images.githubusercontent.com/39267501/62629358-4abbcf80-b92d-11e9-89e7-3d3015870743.png)

If you have any suggestions or ideas for this section, please leave a comment:)

Thanks!

**Comment by majo44** [comment]
https://css-tricks.com/creating-responsive-touch-friendly-carousels-with-flickity/
